#!/usr/bin/env bun
/**
 * BackupRestore - Backup, restore, and upgrade PAI installations
 *
 * Commands:
 *   backup [--name <label>]                          - Create timestamped backup of ~/.claude
 *   backup --user-only --release <path>              - Back up only files that differ from release
 *   restore <backup-name>                            - Restore from backup
 *   list                                             - List available backups
 *   migrate <backup>                                 - Analyze backup for migration candidates
 *   diff --release <path>                            - Compare local install against a release
 *   upgrade --release <path>                         - Safe upgrade with automatic backup/restore
 *
 * Usage:
 *   bun BackupRestore.ts backup
 *   bun BackupRestore.ts backup --name "before-upgrade"
 *   bun BackupRestore.ts backup --user-only --release ./Releases/v4.1.0/.claude
 *   bun BackupRestore.ts list
 *   bun BackupRestore.ts restore claude-backup-20260114-153000
 *   bun BackupRestore.ts migrate claude-backup-20260114-153000
 *   bun BackupRestore.ts diff --release ./Releases/v4.1.0/.claude
 *   bun BackupRestore.ts upgrade --release ./Releases/v4.1.0/.claude
 */

import {
  existsSync,
  readdirSync,
  statSync,
  readFileSync,
  cpSync,
  rmSync,
  mkdirSync,
  writeFileSync,
} from "fs";
import { homedir } from "os";
import { join, basename, relative, dirname } from "path";
import { createHash } from "crypto";
import { execSync } from "child_process";

const HOME = homedir();
const CLAUDE_DIR = join(HOME, ".claude");
const BACKUP_PREFIX = "claude-backup-";
const USER_BACKUP_PREFIX = "claude-user-backup-";

// Files that should not be restored during upgrade because they are regenerated:
// - CLAUDE.md: regenerated by BuildCLAUDE.ts from template + settings.json
//
// Note: settings.json IS restored before install.sh runs, so that install.sh's
// merge logic reads the user's existing config (hooks, statusLine, etc.) and
// only updates version/identity fields.
const UPGRADE_SKIP_RESTORE = new Set(["CLAUDE.md"]);

// Claude Code runtime directories with no user value — excluded from user-only backup.
// These are machine-specific, session-specific, or auto-regenerated.
const CC_RUNTIME_EXCLUDE = new Set([
  "debug",
  "todos",
  "session-env",
  "sessions",
  "shell-snapshots",
  "paste-cache",
  "cache",
  "image-cache",
  "telemetry",
  "backups",
  "claude-history-md",
]);

/**
 * Parse a .gitignore file and return a list of patterns.
 * Supports simple filename matches (e.g., ".DS_Store", "*.log")
 * and directory patterns (e.g., "node_modules/").
 * Does not support negation (!) or complex glob patterns.
 */
function parseGitignore(gitignorePath: string): string[] {
  if (!existsSync(gitignorePath)) return [];
  try {
    return readFileSync(gitignorePath, "utf-8")
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#"));
  } catch {
    return [];
  }
}

/**
 * Check if a relative file path matches any gitignore pattern.
 */
function isIgnored(relPath: string, patterns: string[]): boolean {
  const fileName = basename(relPath);
  const parts = relPath.split("/");

  for (const pattern of patterns) {
    // Directory pattern: "node_modules/" matches any path segment
    if (pattern.endsWith("/")) {
      const dirName = pattern.slice(0, -1);
      if (parts.includes(dirName)) return true;
      continue;
    }

    // Wildcard pattern: "*.log" matches file extension
    if (pattern.startsWith("*.")) {
      const ext = pattern.slice(1); // ".log"
      if (fileName.endsWith(ext)) return true;
      continue;
    }

    // Prefix pattern: "._*" matches filenames starting with prefix
    if (pattern.endsWith("*")) {
      const prefix = pattern.slice(0, -1);
      if (fileName.startsWith(prefix)) return true;
      continue;
    }

    // Exact filename match: ".DS_Store"
    if (fileName === pattern) return true;

    // Path match: "private/" or ".claude/pai_updates/"
    if (relPath === pattern || relPath.startsWith(pattern + "/")) return true;
  }

  return false;
}

/**
 * Find and load .gitignore from the repo root (parent of release dir).
 * Walks up from the release directory looking for .gitignore.
 */
function loadIgnorePatterns(releaseDir: string): string[] {
  // Walk up to find repo root .gitignore
  let dir = releaseDir;
  for (let i = 0; i < 5; i++) {
    const gitignorePath = join(dir, ".gitignore");
    if (existsSync(gitignorePath)) {
      return parseGitignore(gitignorePath);
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // Fallback: minimal ignore list
  return [".DS_Store", "Thumbs.db"];
}

// ============================================================================
// Types
// ============================================================================

interface BackupInfo {
  name: string;
  path: string;
  date: Date;
  size: string;
  hasSettings: boolean;
  hasHooks: boolean;
  hasSkills: boolean;
}

interface MigrationCandidate {
  type: "settings" | "hook" | "skill" | "memory";
  path: string;
  description: string;
}

interface DiffResult {
  newFiles: string[]; // In release but not in local
  unchanged: string[]; // In both, same hash
  conflicts: string[]; // In both, different hash
  releaseDir: string;
}

// ============================================================================
// Utilities
// ============================================================================

function formatDate(date: Date): string {
  return date.toISOString().replace(/[:.]/g, "-").slice(0, 19);
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1024 * 1024 * 1024)
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(1)} GB`;
}

function getDirSize(dirPath: string): number {
  let size = 0;
  try {
    const files = readdirSync(dirPath, { withFileTypes: true });
    for (const file of files) {
      const filePath = join(dirPath, file.name);
      if (file.isDirectory()) {
        size += getDirSize(filePath);
      } else {
        size += statSync(filePath).size;
      }
    }
  } catch {
    // Ignore errors (permission issues, etc.)
  }
  return size;
}

function sha256(filePath: string): string {
  const content = readFileSync(filePath);
  return createHash("sha256").update(content).digest("hex");
}

/**
 * Recursively list all files in a directory, returning paths relative to root.
 */
function listFiles(dir: string, root?: string): string[] {
  const base = root || dir;
  const results: string[] = [];

  try {
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        results.push(...listFiles(fullPath, base));
      } else if (entry.isFile()) {
        results.push(relative(base, fullPath));
      }
    }
  } catch {
    // Ignore permission errors
  }

  return results;
}

/**
 * Compare a release directory against the local ~/.claude/ installation.
 * Returns categorized file lists.
 */
function diffRelease(releaseDir: string): DiffResult {
  const releaseFiles = listFiles(releaseDir);
  const ignorePatterns = loadIgnorePatterns(releaseDir);
  const newFiles: string[] = [];
  const unchanged: string[] = [];
  const conflicts: string[] = [];

  for (const relPath of releaseFiles) {
    // Skip files matching .gitignore patterns
    if (isIgnored(relPath, ignorePatterns)) continue;

    // Skip PAI/USER/ — everything under there is user data,
    // always preserved, never treated as a conflict
    if (relPath.startsWith("PAI/USER/")) continue;

    // Skip MEMORY/ — everything under there is user data,
    // always preserved, never treated as a conflict
    if (relPath.startsWith("MEMORY/")) continue;

    // Skip PAI-Install/ — this is the official installer,
    // always replaced by the release, never user data
    if (relPath.startsWith("PAI-Install/")) continue;

    // Skip settings.json — always backed up as user data,
    // restored before install.sh which handles the merge
    if (relPath === "settings.json") continue;

    const localPath = join(CLAUDE_DIR, relPath);
    const releasePath = join(releaseDir, relPath);

    if (!existsSync(localPath)) {
      newFiles.push(relPath);
    } else {
      const localHash = sha256(localPath);
      const releaseHash = sha256(releasePath);

      if (localHash === releaseHash) {
        unchanged.push(relPath);
      } else {
        conflicts.push(relPath);
      }
    }
  }

  return { newFiles, unchanged, conflicts, releaseDir };
}

function listBackups(): BackupInfo[] {
  const backups: BackupInfo[] = [];

  try {
    const entries = readdirSync(HOME, { withFileTypes: true });
    for (const entry of entries) {
      if (
        entry.isDirectory() &&
        (entry.name.startsWith(BACKUP_PREFIX) ||
          entry.name.startsWith(USER_BACKUP_PREFIX))
      ) {
        const backupPath = join(HOME, entry.name);
        const stats = statSync(backupPath);
        const size = getDirSize(backupPath);

        backups.push({
          name: entry.name,
          path: backupPath,
          date: stats.mtime,
          size: formatSize(size),
          hasSettings: existsSync(join(backupPath, "settings.json")),
          hasHooks: existsSync(join(backupPath, "hooks")),
          hasSkills: existsSync(join(backupPath, "skills")),
        });
      }
    }
  } catch (error) {
    console.error("Error listing backups:", error);
  }

  return backups.sort((a, b) => b.date.getTime() - a.date.getTime());
}

function createBackup(customName?: string): string | null {
  if (!existsSync(CLAUDE_DIR)) {
    console.error(
      "Error: ~/.claude directory does not exist. Nothing to backup."
    );
    return null;
  }

  const timestamp = formatDate(new Date()).replace("T", "-");
  const backupName = customName
    ? `${BACKUP_PREFIX}${customName}-${timestamp}`
    : `${BACKUP_PREFIX}${timestamp}`;
  const backupPath = join(HOME, backupName);

  if (existsSync(backupPath)) {
    console.error(`Error: Backup already exists at ${backupPath}`);
    return null;
  }

  console.log(`Creating backup: ${backupName}`);
  console.log(`Source: ${CLAUDE_DIR}`);
  console.log(`Destination: ${backupPath}`);

  try {
    cpSync(CLAUDE_DIR, backupPath, { recursive: true });
    const size = getDirSize(backupPath);
    console.log(`\nBackup complete: ${formatSize(size)}`);
    console.log(`Location: ~/${backupName}`);
    return backupName;
  } catch (error) {
    console.error("Error creating backup:", error);
    return null;
  }
}

function restoreBackup(backupName: string): boolean {
  // Handle both full path and just the name
  const backupPath = backupName.startsWith("/")
    ? backupName
    : join(
        HOME,
        backupName.startsWith(BACKUP_PREFIX)
          ? backupName
          : `${BACKUP_PREFIX}${backupName}`
      );

  if (!existsSync(backupPath)) {
    console.error(`Error: Backup not found at ${backupPath}`);
    console.log("\nAvailable backups:");
    const backups = listBackups();
    backups.forEach((b) => console.log(`  - ${b.name}`));
    return false;
  }

  // Backup current before restore
  if (existsSync(CLAUDE_DIR)) {
    const preRestoreBackup = createBackup("pre-restore");
    if (!preRestoreBackup) {
      console.error("Failed to create pre-restore backup. Aborting.");
      return false;
    }
    console.log(`\nCurrent installation backed up to: ${preRestoreBackup}`);

    // Remove current
    console.log("Removing current installation...");
    rmSync(CLAUDE_DIR, { recursive: true, force: true });
  }

  console.log(`\nRestoring from: ${backupPath}`);
  console.log(`Destination: ${CLAUDE_DIR}`);

  try {
    cpSync(backupPath, CLAUDE_DIR, { recursive: true });
    console.log("\nRestore complete!");
    console.log("Restart your DA session for changes to take effect.");
    return true;
  } catch (error) {
    console.error("Error restoring backup:", error);
    return false;
  }
}

function analyzeMigration(backupName: string): MigrationCandidate[] {
  const backupPath = backupName.startsWith("/")
    ? backupName
    : join(
        HOME,
        backupName.startsWith(BACKUP_PREFIX)
          ? backupName
          : `${BACKUP_PREFIX}${backupName}`
      );

  if (!existsSync(backupPath)) {
    console.error(`Error: Backup not found at ${backupPath}`);
    return [];
  }

  const candidates: MigrationCandidate[] = [];

  // Check settings.json
  const settingsPath = join(backupPath, "settings.json");
  if (existsSync(settingsPath)) {
    try {
      const settings = JSON.parse(readFileSync(settingsPath, "utf-8"));

      if (settings.daidentity) {
        candidates.push({
          type: "settings",
          path: "settings.json → daidentity",
          description: `DA Identity: ${settings.daidentity.name || "unnamed"} (${settings.daidentity.fullName || ""})`,
        });
      }

      if (settings.principal) {
        candidates.push({
          type: "settings",
          path: "settings.json → principal",
          description: `Principal: ${settings.principal.name || "unnamed"} (${settings.principal.timezone || ""})`,
        });
      }

      if (settings.hooks) {
        const hookCount = Object.keys(settings.hooks).length;
        candidates.push({
          type: "settings",
          path: "settings.json → hooks",
          description: `${hookCount} hook event(s) configured`,
        });
      }
    } catch {
      console.warn("Warning: Could not parse settings.json");
    }
  }

  // Check for custom hooks
  const hooksDir = join(backupPath, "hooks");
  if (existsSync(hooksDir)) {
    try {
      const hooks = readdirSync(hooksDir).filter((f) =>
        f.endsWith(".hook.ts")
      );
      for (const hook of hooks) {
        candidates.push({
          type: "hook",
          path: `hooks/${hook}`,
          description: `Custom hook: ${hook.replace(".hook.ts", "")}`,
        });
      }
    } catch {
      // Ignore errors
    }
  }

  // Check for personal skills (_ALLCAPS)
  const skillsDir = join(backupPath, "skills");
  if (existsSync(skillsDir)) {
    try {
      const skills = readdirSync(skillsDir, { withFileTypes: true })
        .filter((d) => d.isDirectory() && d.name.startsWith("_"))
        .map((d) => d.name);

      for (const skill of skills) {
        candidates.push({
          type: "skill",
          path: `skills/${skill}`,
          description: `Personal skill: ${skill} (private, not shared)`,
        });
      }
    } catch {
      // Ignore errors
    }
  }

  // Check for MEMORY content
  const memoryDir = join(backupPath, "MEMORY");
  if (existsSync(memoryDir)) {
    try {
      const subdirs = readdirSync(memoryDir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name);

      if (subdirs.length > 0) {
        candidates.push({
          type: "memory",
          path: "MEMORY/",
          description: `Memory directories: ${subdirs.join(", ")}`,
        });
      }
    } catch {
      // Ignore errors
    }
  }

  return candidates;
}

/**
 * diff --release <path>
 * Compare local installation against a release directory.
 */
function cmdDiff(releaseDir: string): DiffResult {
  if (!existsSync(releaseDir)) {
    console.error(`Error: Release directory not found: ${releaseDir}`);
    process.exit(1);
  }

  if (!existsSync(CLAUDE_DIR)) {
    console.error("Error: ~/.claude directory does not exist.");
    process.exit(1);
  }

  const result = diffRelease(releaseDir);

  console.log();
  console.log("══════════════════════════════════════════════════════");
  console.log(" PAI UPGRADE · Diff");
  console.log("══════════════════════════════════════════════════════");
  console.log();
  console.log(`  Release: ${releaseDir}`);
  console.log(`  Local:   ${CLAUDE_DIR}`);
  console.log();
  console.log(
    `  New files (will be added):         ${result.newFiles.length.toString().padStart(5)}`
  );
  console.log(
    `  Unchanged (identical):             ${result.unchanged.length.toString().padStart(5)}`
  );
  console.log(
    `  Conflicts (local modified):        ${result.conflicts.length.toString().padStart(5)}`
  );

  if (result.conflicts.length > 0) {
    // Separate auto-handled files from real user conflicts
    const autoHandled = result.conflicts.filter((f) =>
      UPGRADE_SKIP_RESTORE.has(f)
    );
    const userConflicts = result.conflicts.filter(
      (f) => !UPGRADE_SKIP_RESTORE.has(f)
    );

    if (autoHandled.length > 0) {
      console.log();
      console.log("  Auto-regenerated (backed up but not restored):");
      for (const file of autoHandled) {
        console.log(`    ⊘ ${file} (regenerated by BuildCLAUDE.ts)`);
      }
    }

    if (userConflicts.length > 0) {
      console.log();
      console.log("  User conflicts (will be backed up):");
      for (const file of userConflicts) {
        console.log(`    ~ ${file}`);
      }
      console.log();
      console.log(
        "  These files exist locally with different content."
      );
      console.log(
        "  Use backup --user-only to save them. You can review the"
      );
      console.log(
        "  backup and remove files you don't want to keep before"
      );
      console.log("  running upgrade.");
    }
  } else {
    console.log();
    console.log("  No conflicts. Upgrade is safe to proceed.");
  }

  console.log();
  console.log("══════════════════════════════════════════════════════");
  console.log();

  return result;
}

/**
 * backup --user-only --release <path>
 * Back up only files that would be overwritten during upgrade (conflicts).
 */
function createUserOnlyBackup(
  releaseDir: string,
  customName?: string,
  excludeFiles?: string[]
): string | null {
  if (!existsSync(releaseDir)) {
    console.error(`Error: Release directory not found: ${releaseDir}`);
    return null;
  }

  const result = diffRelease(releaseDir);

  // Always include settings.json — it's user data
  const settingsPath = join(CLAUDE_DIR, "settings.json");
  if (existsSync(settingsPath) && !result.conflicts.includes("settings.json")) {
    result.conflicts.push("settings.json");
  }

  // Always include CLAUDE.md — backed up (though not restored; BuildCLAUDE.ts regenerates it)
  const claudeMdPath = join(CLAUDE_DIR, "CLAUDE.md");
  if (existsSync(claudeMdPath) && !result.conflicts.includes("CLAUDE.md")) {
    result.conflicts.push("CLAUDE.md");
  }

  // Always include these directories — they are always user data
  const alwaysBackupDirs = [
    join(CLAUDE_DIR, "PAI", "USER"),
    join(CLAUDE_DIR, "MEMORY"),
  ];
  const ignorePatterns = loadIgnorePatterns(releaseDir);
  for (const dir of alwaysBackupDirs) {
    if (!existsSync(dir)) continue;
    const userFiles = listFiles(dir, CLAUDE_DIR);
    for (const f of userFiles) {
      if (!result.conflicts.includes(f) && !isIgnored(f, ignorePatterns)) {
        result.conflicts.push(f);
      }
    }
  }

  // Include all local files that don't exist in the release — these are
  // purely user-generated (MEMORY/ contents, custom_skill/, kb/, bots/, etc.)
  const releaseFileSet = new Set(listFiles(releaseDir));
  const localFiles = listFiles(CLAUDE_DIR);
  for (const f of localFiles) {
    if (result.conflicts.includes(f)) continue;
    if (isIgnored(f, ignorePatterns)) continue;
    if (f.startsWith("PAI/USER/")) continue; // already handled above

    // Skip CC runtime directories (no user value)
    const topDir = f.split("/")[0];
    if (CC_RUNTIME_EXCLUDE.has(topDir)) continue;

    // Skip PAI-Install/ — always replaced by the release
    if (f.startsWith("PAI-Install/")) continue;

    if (releaseFileSet.has(f)) continue; // exists in release, handled by diff
    result.conflicts.push(f);
  }

  // Apply user-specified excludes as the final filter
  if (excludeFiles && excludeFiles.length > 0) {
    const excludeSet = new Set(excludeFiles);
    result.conflicts = result.conflicts.filter((f) => !excludeSet.has(f));
  }

  if (result.conflicts.length === 0) {
    console.log("\nNo user data to back up (after exclusions).");
    return null;
  }

  const timestamp = formatDate(new Date()).replace("T", "-");
  const backupName = customName
    ? `${USER_BACKUP_PREFIX}${customName}-${timestamp}`
    : `${USER_BACKUP_PREFIX}${timestamp}`;
  const backupPath = join(HOME, backupName);

  if (existsSync(backupPath)) {
    console.error(`Error: Backup already exists at ${backupPath}`);
    return null;
  }

  console.log(`\nBacking up ${result.conflicts.length} conflicting file(s)...`);

  mkdirSync(backupPath, { recursive: true });

  let totalSize = 0;

  for (const relPath of result.conflicts) {
    const srcPath = join(CLAUDE_DIR, relPath);
    const dstPath = join(backupPath, relPath);
    const dstDir = dirname(dstPath);

    mkdirSync(dstDir, { recursive: true });
    cpSync(srcPath, dstPath);
    totalSize += statSync(srcPath).size;
  }

  // Write a manifest of what was backed up
  const manifest = {
    type: "user-only",
    timestamp: new Date().toISOString(),
    releaseDir,
    conflicts: result.conflicts,
    totalFiles: result.conflicts.length,
    totalSize,
  };
  writeFileSync(
    join(backupPath, "backup-manifest.json"),
    JSON.stringify(manifest, null, 2)
  );

  console.log();
  console.log("══════════════════════════════════════════════════════");
  console.log(" PAI BACKUP · User-Only");
  console.log("══════════════════════════════════════════════════════");
  console.log();
  console.log(`  Files backed up: ${result.conflicts.length}`);
  console.log(`  Total size:      ${formatSize(totalSize)}`);
  console.log(`  Location:        ~/${backupName}`);
  console.log();
  console.log("  Files:");
  for (const file of result.conflicts) {
    console.log(`    ${file}`);
  }
  console.log();
  console.log(
    "  Review the backup directory and remove any files you"
  );
  console.log(
    "  don't want restored after upgrade."
  );
  console.log();
  console.log("══════════════════════════════════════════════════════");
  console.log();

  return backupName;
}

/**
 * Find the most recent user-only backup.
 */
function findLatestUserBackup(): string | null {
  try {
    const entries = readdirSync(HOME, { withFileTypes: true });
    const userBackups = entries
      .filter(
        (e) => e.isDirectory() && e.name.startsWith(USER_BACKUP_PREFIX)
      )
      .map((e) => ({
        name: e.name,
        mtime: statSync(join(HOME, e.name)).mtimeMs,
      }))
      .sort((a, b) => b.mtime - a.mtime);

    return userBackups.length > 0 ? userBackups[0].name : null;
  } catch {
    return null;
  }
}

/**
 * Find the most recent full backup.
 */
function findLatestFullBackup(): string | null {
  try {
    const entries = readdirSync(HOME, { withFileTypes: true });
    const fullBackups = entries
      .filter(
        (e) =>
          e.isDirectory() &&
          e.name.startsWith(BACKUP_PREFIX) &&
          !e.name.startsWith(USER_BACKUP_PREFIX)
      )
      .map((e) => ({
        name: e.name,
        mtime: statSync(join(HOME, e.name)).mtimeMs,
      }))
      .sort((a, b) => b.mtime - a.mtime);

    return fullBackups.length > 0 ? fullBackups[0].name : null;
  } catch {
    return null;
  }
}

/**
 * upgrade --release <path>
 * Full upgrade cycle: diff → backup → cp -r → restore user files → install → build
 */
function cmdUpgrade(releaseDir: string): void {
  if (!existsSync(releaseDir)) {
    console.error(`Error: Release directory not found: ${releaseDir}`);
    process.exit(1);
  }

  console.log();
  console.log("══════════════════════════════════════════════════════");
  console.log(" PAI UPGRADE");
  console.log("══════════════════════════════════════════════════════");
  console.log();

  // Check for recent full backup
  const latestFull = findLatestFullBackup();
  if (!latestFull) {
    console.error(
      "  ⚠  No full backup found. Please run a full backup first:"
    );
    console.error("     bun Tools/BackupRestore.ts backup --name pre-upgrade");
    console.error(
      "\n  A full backup is required as a safety net before upgrading."
    );
    process.exit(1);
  }

  const fullBackupAge =
    Date.now() - statSync(join(HOME, latestFull)).mtimeMs;
  const fullBackupAgeHours = Math.round(fullBackupAge / (1000 * 60 * 60));

  if (fullBackupAgeHours > 24) {
    console.log(
      `  ⚠  Latest full backup is ${fullBackupAgeHours}h old: ${latestFull}`
    );
    console.log("     Consider running a fresh backup first.");
    console.log();
  } else {
    console.log(`  ✓ Full backup found: ${latestFull}`);
  }

  // Step 1: Diff
  console.log("\n  Step 1/5: Analyzing differences...\n");
  const diff = diffRelease(releaseDir);

  console.log(`  New files:   ${diff.newFiles.length}`);
  console.log(`  Unchanged:   ${diff.unchanged.length}`);
  console.log(`  Conflicts:   ${diff.conflicts.length}`);

  if (diff.conflicts.length === 0) {
    console.log("\n  No conflicts. Proceeding with upgrade...\n");
  } else {
    // Step 2: Backup conflicts
    console.log("\n  Step 2/5: Backing up conflicting files...\n");

    const userBackupName = createUserOnlyBackup(releaseDir);
    if (!userBackupName && diff.conflicts.length > 0) {
      console.error("  Failed to create user backup. Aborting.");
      process.exit(1);
    }
  }

  // Step 3: Copy release files
  console.log("  Step 3/5: Applying release...\n");
  try {
    cpSync(releaseDir, CLAUDE_DIR, { recursive: true });
    console.log("  ✓ Release files copied.\n");
  } catch (error) {
    console.error("  ✗ Failed to copy release files:", error);
    console.error(`\n  Restore from full backup: ${latestFull}`);
    process.exit(1);
  }

  // Step 4: Restore user modifications
  if (diff.conflicts.length > 0) {
    console.log("  Step 4/5: Restoring user modifications...\n");

    const latestUser = findLatestUserBackup();
    if (latestUser) {
      const userBackupPath = join(HOME, latestUser);
      const manifestPath = join(userBackupPath, "backup-manifest.json");
      let filesToRestore: string[] = [];

      if (existsSync(manifestPath)) {
        const manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
        filesToRestore = manifest.conflicts || [];
      } else {
        // Fallback: restore all files in the backup directory
        filesToRestore = listFiles(userBackupPath).filter(
          (f) => f !== "backup-manifest.json"
        );
      }

      let restored = 0;
      let skipped = 0;

      for (const relPath of filesToRestore) {
        // Skip files that have special merge handling
        if (UPGRADE_SKIP_RESTORE.has(relPath)) {
          console.log(`    ⊘ ${relPath} (handled by install.sh)`);
          skipped++;
          continue;
        }

        const srcPath = join(userBackupPath, relPath);
        const dstPath = join(CLAUDE_DIR, relPath);

        if (existsSync(srcPath)) {
          const dstDir = dirname(dstPath);
          mkdirSync(dstDir, { recursive: true });
          cpSync(srcPath, dstPath);
          console.log(`    ✓ ${relPath}`);
          restored++;
        }
      }

      console.log(
        `\n  Restored ${restored} file(s), skipped ${skipped}.\n`
      );
    }
  } else {
    console.log("  Step 4/5: No conflicts to restore.\n");
  }

  // Step 5: Run BuildCLAUDE.ts
  console.log("  Step 5/5: Rebuilding CLAUDE.md...\n");
  const buildScript = join(CLAUDE_DIR, "PAI", "Tools", "BuildCLAUDE.ts");
  if (existsSync(buildScript)) {
    try {
      execSync(`bun "${buildScript}"`, { stdio: "inherit" });
      console.log();
    } catch {
      console.log("  ⚠  BuildCLAUDE.ts failed. Run manually:");
      console.log(`     bun "${buildScript}"\n`);
    }
  } else {
    console.log("  ⚠  BuildCLAUDE.ts not found. Skipping.\n");
  }

  console.log("══════════════════════════════════════════════════════");
  console.log(" Upgrade complete!");
  console.log();
  console.log(" Next steps:");
  console.log("   1. Run install.sh if you need to update identity/voice:");
  console.log("      cd ~/.claude && bash install.sh");
  console.log("   2. Restart Claude Code to pick up changes.");
  console.log("══════════════════════════════════════════════════════");
  console.log();
}

function printUsage(): void {
  console.log(`
PAI Backup & Restore Tool

Usage:
  bun BackupRestore.ts <command> [options]

Commands:
  backup [--name <label>]                          Create timestamped backup of ~/.claude
  backup --user-only --release <path>              Back up only files that differ from release
  restore <backup-name>                            Restore from backup (creates pre-restore backup first)
  list                                             List available backups
  migrate <backup>                                 Analyze backup for migration candidates
  diff --release <path>                            Compare local install against a release
  upgrade --release <path>                         Safe upgrade with automatic backup/restore

Upgrade Flow:
  1. bun BackupRestore.ts diff --release ./Releases/v4.1.0/.claude
  2. bun BackupRestore.ts backup --name "pre-v4.1"              # REQUIRED: full safety backup
  3. bun BackupRestore.ts backup --user-only --release ./Releases/v4.1.0/.claude
  4. bun BackupRestore.ts upgrade --release ./Releases/v4.1.0/.claude

Notes:
  - Backups are stored in your home directory (~/)
  - Full backups use prefix "${BACKUP_PREFIX}"
  - User-only backups use prefix "${USER_BACKUP_PREFIX}"
  - Restore always creates a pre-restore backup of current installation
  - settings.json is handled by install.sh's merge logic, not by user-only restore
`);
}

// Main CLI
const args = process.argv.slice(2);
const command = args[0];

function getReleasePath(): string {
  const releaseIndex = args.indexOf("--release");
  if (releaseIndex === -1 || !args[releaseIndex + 1]) {
    console.error("Error: --release <path> is required.");
    console.error(
      "  Provide the path to a release .claude directory, e.g.:"
    );
    console.error(
      "  bun BackupRestore.ts diff --release ./Releases/v4.1.0/.claude"
    );
    process.exit(1);
  }
  return args[releaseIndex + 1];
}

switch (command) {
  case "backup": {
    const isUserOnly = args.includes("--user-only");

    if (isUserOnly) {
      const releaseDir = getReleasePath();
      let customName: string | undefined;
      const nameIndex = args.indexOf("--name");
      if (nameIndex !== -1 && args[nameIndex + 1]) {
        customName = args[nameIndex + 1];
      }
      // Collect --exclude arguments
      const excludeFiles: string[] = [];
      let idx = args.indexOf("--exclude");
      while (idx !== -1) {
        if (args[idx + 1]) excludeFiles.push(args[idx + 1]);
        idx = args.indexOf("--exclude", idx + 1);
      }
      createUserOnlyBackup(releaseDir, customName, excludeFiles);
    } else {
      let customName: string | undefined;
      const nameIndex = args.indexOf("--name");
      if (nameIndex !== -1 && args[nameIndex + 1]) {
        customName = args[nameIndex + 1];
      }
      createBackup(customName);
    }
    break;
  }

  case "restore": {
    const backupName = args[1];
    if (!backupName) {
      console.error("Error: Please specify a backup name to restore.");
      console.log("\nAvailable backups:");
      const backups = listBackups();
      backups.forEach((b) => console.log(`  - ${b.name}`));
      process.exit(1);
    }
    restoreBackup(backupName);
    break;
  }

  case "list": {
    const backups = listBackups();
    if (backups.length === 0) {
      console.log("No backups found.");
      console.log(
        `\nBackups are stored in ~/ with prefix "${BACKUP_PREFIX}" or "${USER_BACKUP_PREFIX}"`
      );
    } else {
      console.log("Available backups:\n");
      for (const backup of backups) {
        const isUserOnly = backup.name.startsWith(USER_BACKUP_PREFIX);
        const tag = isUserOnly ? " [user-only]" : "";
        console.log(`${backup.name}${tag}`);
        console.log(`  Date: ${backup.date.toLocaleString()}`);
        console.log(`  Size: ${backup.size}`);
        if (!isUserOnly) {
          console.log(
            `  Contents: ${[
              backup.hasSettings ? "settings" : "",
              backup.hasHooks ? "hooks" : "",
              backup.hasSkills ? "skills" : "",
            ]
              .filter(Boolean)
              .join(", ") || "empty"}`
          );
        }
        console.log("");
      }
    }
    break;
  }

  case "migrate": {
    const backupName = args[1];
    if (!backupName) {
      console.error("Error: Please specify a backup name to analyze.");
      console.log("\nAvailable backups:");
      const backups = listBackups();
      backups.forEach((b) => console.log(`  - ${b.name}`));
      process.exit(1);
    }

    const candidates = analyzeMigration(backupName);
    if (candidates.length === 0) {
      console.log("No migration candidates found in this backup.");
    } else {
      console.log("Migration candidates:\n");

      const byType = {
        settings: candidates.filter((c) => c.type === "settings"),
        hook: candidates.filter((c) => c.type === "hook"),
        skill: candidates.filter((c) => c.type === "skill"),
        memory: candidates.filter((c) => c.type === "memory"),
      };

      if (byType.settings.length > 0) {
        console.log("Settings (can merge into new settings.json):");
        byType.settings.forEach((c) => console.log(`  - ${c.description}`));
        console.log("");
      }

      if (byType.hook.length > 0) {
        console.log("Custom Hooks (copy to new hooks/ directory):");
        byType.hook.forEach((c) => console.log(`  - ${c.path}`));
        console.log("");
      }

      if (byType.skill.length > 0) {
        console.log("Personal Skills (copy to new skills/ directory):");
        byType.skill.forEach((c) => console.log(`  - ${c.path}`));
        console.log("");
      }

      if (byType.memory.length > 0) {
        console.log("Memory Data (can be preserved):");
        byType.memory.forEach((c) => console.log(`  - ${c.description}`));
        console.log("");
      }

      console.log(
        "To migrate these items, use your DA to selectively copy"
      );
      console.log(
        "the desired files from the backup to your new PAI installation."
      );
    }
    break;
  }

  case "diff": {
    const releaseDir = getReleasePath();
    cmdDiff(releaseDir);
    break;
  }

  case "upgrade": {
    const releaseDir = getReleasePath();
    cmdUpgrade(releaseDir);
    break;
  }

  default:
    printUsage();
    if (
      command &&
      command !== "help" &&
      command !== "--help" &&
      command !== "-h"
    ) {
      console.error(`\nUnknown command: ${command}`);
      process.exit(1);
    }
}
